# Generated by Django 5.0.5 on 2024-06-18 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inmueble.property'),
        ),
    ]
